name: RFC XML Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: |
        sudo apt-get install cmake libxml2-utils xml2rfc
    - name: xml2rfc
      run: |
        mkdir -p spec/build
        (cd spec/build && cmake ..)
        cmake --build spec/build
    - uses: actions/upload-artifact@v2
      with:
        name: spec
        path: |
          spec/build/draft-*.html
          spec/build/draft-*.txt
          spec/build/misspelling.txt
