name: Wireshark Plugin

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: |
        sudo apt-get install cmake wireshark-dev libgcrypt-dev gnutls-dev libgtest-dev
        # Annoying need on Ubuntu 18.04
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp *.a /usr/lib
    - name: configure
      run: |
        mkdir wireshark-plugin/build
        cd wireshark-plugin/build
        cmake ..
    - name: build
      run: cmake --build wireshark-plugin/build/ --target all
    - name: check
      run: |
        cd wireshark-plugin/build
        ctest -V
